server {
    listen 443 ssl;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;
    
    root /var/www/wordpress;
    index index.php index.html;
    server_name ybassour.42.fr;
    client_max_body_size 100M; 
    location /adminer/ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/adminer/index.php;
        fastcgi_pass adminer:9000;
    
    }
    location /cadvisor/ {
        proxy_pass http://cadvisor:8080/;
        proxy_redirect / /cadvisor/;
    }
    
    location /static_site/ {
        proxy_pass http://static_site:80/;
    }
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass wordpress:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}

